version: "3"

volumes:
  nginxproxymanager-data:
  nginxproxymanager-ssl:
  nginxproxymanager-db:

services:
  nginxproxymanager:
    image: "jc21/nginx-proxy-manager:latest"
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    environment:
      DB_MYSQL_HOST: "nginxproxymanager-db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "securepassword"
      DB_MYSQL_PASSWORD: "securepassword"
      DB_MYSQL_NAME: "securepassword"
    volumes:
      - nginxproxymanager-data:/data
      - nginxproxymanager-ssl:/etc/letsencrypt
  nginxproxymanager-db:
    image: "jc21/mariadb-aria:latest"
    environment:
      MYSQL_ROOT_PASSWORD: "securepassword"
      MYSQL_DATABASE: "securepassword"
      MYSQL_USER: "securepassword"
      MYSQL_PASSWORD: "securepassword"
    volumes:
      - nginxproxymanager-db:/var/lib/mysql
