---
version: "3"

volumes:
  jellyfin-data:
  media-movies:
    external: true
  media-shows:
    external: true

services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/London
      # - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - jellyfin-data:/config
      - media-shows:/data/tvshows
      - media-movies:/data/movies
    networks:
      empire:
        ipv4_address: 10.10.10.254
    # uncomment ports if not using vlan network
    # ports:
    #   - 8096:8096
    #   - 8920:8920 #optional
    #   - 7359:7359/udp #optional
    #   - 1900:1900/udp #optional
    restart: always

networks:
  empire:
    external: true
