---
version: "3"

volumes:
  ombi-data:

services:
  ombi:
    image: linuxserver/ombi:latest
    container_name: ombi
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/London
      - BASE_URL=/ombi #optional
    volumes:
      - ombi-data:/config
    networks:
      empire:
        ipv4_address: 10.10.10.253
      correlian:
    restart: always

networks:
  empire:
    external: true
  correlian:
    external: true
