---
version: "3"

volumes:
  prometheus-data:
  grafana-data:

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - /srv/dev-disk-by-uuid-0d4a201c-b292-412d-ade6-cc5561e54f1f/Configs/Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9292:9090
    restart: unless-stopped
    networks:
      - republic

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - republic

networks:
  # private:
  republic:
    external: true
